image: ubuntu/lts
secrets:
  - b2452f2e-0188-49c2-abce-25634fa37505 # sr.ht ssh key
sources:
  - git@git.sr.ht:~reykjalin/inner_circle
artifacts:
  - inner_circle.tar.gz
repositories:
  erlang-solutions: https://packages.erlang-solutions.com/ubuntu focal contrib D208507CA14F4FCA
packages:
  - esl-erlang
  - elixir
tasks:
  - node: |
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      . $HOME/.nvm/nvm.sh
      nvm install --lts
  - setup: |
      . $HOME/.nvm/nvm.sh
      nvm use --lts
      cd inner_circle
      mix local.hex --force
      mix local.rebar --force
      mix deps.get --only prod
      MIX_ENV=prod mix compile
      nvm exec npm install --prefix ./assets
  - build: |
      export LANG="en_US.UTF-8"
      export LC_ALL="en_US.UTF-8"
      . $HOME/.nvm/nvm.sh
      nvm use --lts
      cd inner_circle
      nvm exec npm run deploy --prefix ./assets
      MIX_ENV=prod mix phx.digest
      MIX_ENV=prod mix release
  - bundle: |
      tar -czvf inner_circle.tar.gz -C inner_circle/_build/prod/rel/ inner_circle
