# fly.toml app configuration file generated for jarm on 2023-07-20T23:46:14-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jarm"
primary_region = "yyz"
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "jarm.fly.dev"
  PORT = "8080"
  DATABASE_PATH = "/jarm.db"
  URL = ""
  # ADMIN_EMAIL, SMTP_USERNAME, SMTP_PASSWORD, SMTP_SERVER, SMTP_PORT, SECRET_KEY_BASE, LIVE_VIEW_SIGNING_SALT should all be set via fly CLI/dashboard.

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
